"""页面 endpoint → (module, action) 权限映射

key 为 Flask Blueprint 注册后的完整 endpoint 名 (含 Blueprint 前缀)。
新增页面路由时, 在此登记对应权限, before_request 拦截生效。
"""
PAGE_ENDPOINT_PERMISSIONS = {
    'pages.dashboard': ('dashboard', 'view'),
    'pages.materials': ('material', 'view'),
    'pages.material_new': ('material', 'edit'),
    'pages.material_edit': ('material', 'edit'),
    'pages.inventory': ('inventory', 'view'),
    'pages.in_orders': ('in_order', 'view'),
    'pages.in_order_new': ('in_order', 'edit'),
    'pages.in_order_edit': ('in_order', 'edit'),
    'pages.in_order_detail': ('in_order', 'view'),
    'pages.in_order_details': ('in_order', 'view'),
    'pages.out_orders': ('out_order', 'view'),
    'pages.out_order_new': ('out_order', 'edit'),
    'pages.out_order_edit': ('out_order', 'edit'),
    'pages.out_order_detail': ('out_order', 'view'),
    'pages.out_order_print': ('out_order', 'view'),
    'pages.out_order_details': ('out_order', 'view'),
    'pages.suppliers': ('supplier', 'view'),
    'pages.supplier_new': ('supplier', 'edit'),
    'pages.supplier_edit': ('supplier', 'edit'),
    'pages.employees': ('employee', 'view'),
    'pages.employee_new': ('employee', 'edit'),
    'pages.employee_edit': ('employee', 'edit'),
    'pages.report_inventory': ('report_inventory', 'view'),
    'pages.report_in_detail': ('report_in_detail', 'view'),
    'pages.report_out_detail': ('report_out_detail', 'view'),
    'pages.report_summary': ('report_summary', 'view'),
    'pages.report_stock_flow': ('report_stock_flow', 'view'),
    'pages.category_major': ('category_major', 'view'),
    'pages.category_major_new': ('category_major', 'edit'),
    'pages.category_major_edit': ('category_major', 'edit'),
    'pages.category_minor': ('category_minor', 'view'),
    'pages.category_minor_new': ('category_minor', 'edit'),
    'pages.category_minor_edit': ('category_minor', 'edit'),
    'pages.return_orders': ('return_order', 'view'),
    'pages.return_order_new': ('return_order', 'edit'),
    'pages.return_order_edit': ('return_order', 'edit'),
    'pages.return_order_detail': ('return_order', 'view'),
    'pages.return_order_details': ('return_order', 'view'),
    'pages.weight_records': ('weight_record', 'view'),
    'admin_page.roles_page': ('admin_role', 'manage'),
    'admin_page.users_page': ('admin_user', 'manage'),
}
